// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/about-us/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about-us">> = Specific
  const handler = {} as typeof import("../../../app/about-us/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events">> = Specific
  const handler = {} as typeof import("../../../app/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/executives/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/executives">> = Specific
  const handler = {} as typeof import("../../../app/executives/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/from supabase setup (to delete for reference only)/auth/error/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/from supabase setup (to delete for reference only)/auth/error">> = Specific
  const handler = {} as typeof import("../../../app/from supabase setup (to delete for reference only)/auth/error/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/from supabase setup (to delete for reference only)/auth/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/from supabase setup (to delete for reference only)/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../../app/from supabase setup (to delete for reference only)/auth/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/from supabase setup (to delete for reference only)/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/from supabase setup (to delete for reference only)/auth/login">> = Specific
  const handler = {} as typeof import("../../../app/from supabase setup (to delete for reference only)/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/from supabase setup (to delete for reference only)/auth/sign-up-success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/from supabase setup (to delete for reference only)/auth/sign-up-success">> = Specific
  const handler = {} as typeof import("../../../app/from supabase setup (to delete for reference only)/auth/sign-up-success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/from supabase setup (to delete for reference only)/auth/sign-up/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/from supabase setup (to delete for reference only)/auth/sign-up">> = Specific
  const handler = {} as typeof import("../../../app/from supabase setup (to delete for reference only)/auth/sign-up/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/from supabase setup (to delete for reference only)/auth/update-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/from supabase setup (to delete for reference only)/auth/update-password">> = Specific
  const handler = {} as typeof import("../../../app/from supabase setup (to delete for reference only)/auth/update-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/from supabase setup (to delete for reference only)/protected/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/from supabase setup (to delete for reference only)/protected">> = Specific
  const handler = {} as typeof import("../../../app/from supabase setup (to delete for reference only)/protected/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/member-appli/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/member-appli">> = Specific
  const handler = {} as typeof import("../../../app/member-appli/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/survey/add/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/survey/add">> = Specific
  const handler = {} as typeof import("../../../app/survey/add/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/survey/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/survey">> = Specific
  const handler = {} as typeof import("../../../app/survey/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/thesis/add/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/thesis/add">> = Specific
  const handler = {} as typeof import("../../../app/thesis/add/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/thesis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/thesis">> = Specific
  const handler = {} as typeof import("../../../app/thesis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/from supabase setup (to delete for reference only)/auth/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/from supabase setup (to delete for reference only)/auth/confirm">> = Specific
  const handler = {} as typeof import("../../../app/from supabase setup (to delete for reference only)/auth/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/about-us/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/about-us">> = Specific
  const handler = {} as typeof import("../../../app/about-us/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/from supabase setup (to delete for reference only)/protected/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/from supabase setup (to delete for reference only)/protected">> = Specific
  const handler = {} as typeof import("../../../app/from supabase setup (to delete for reference only)/protected/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/member-appli/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/member-appli">> = Specific
  const handler = {} as typeof import("../../../app/member-appli/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
