import type { Metadata } from "next";
import { Oswald, Ubuntu_Sans } from "next/font/google";
import "./globals.css";

const siteName = "ACE CARDS";

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const ubuntu_mono = Ubuntu_Sans({
  variable: "--font-ubuntu-mono",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: siteName,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${oswald.variable}  ${ubuntu_mono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
